//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libra.UserControl.Parametros {
    
    
    public partial class CadastroCaracteristicaDiversa {
        
        /// <summary>
        /// lblCaracteristicasDiversasProdutoReq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCaracteristicasDiversasProdutoReq;
        
        /// <summary>
        /// txtCaracteristicasDiversasProduto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCaracteristicasDiversasProduto;
        
        /// <summary>
        /// rfvCaracteristicasDiversasProduto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCaracteristicasDiversasProduto;
        
        /// <summary>
        /// chkCaracteristicasDiversasProdutoAtivo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkCaracteristicasDiversasProdutoAtivo;
        
        /// <summary>
        /// lbCancelCaracteristicasDiversasProduto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbCancelCaracteristicasDiversasProduto;
        
        /// <summary>
        /// btnSalvarCaracteristicasDiversasProduto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSalvarCaracteristicasDiversasProduto;
    }
}
