//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libra.Communs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libra.Communs.Resources.EnumLocalization", typeof(EnumLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acre.
        /// </summary>
        internal static string UnidadeFederativa_AC {
            get {
                return ResourceManager.GetString("UnidadeFederativa_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alagoas.
        /// </summary>
        internal static string UnidadeFederativa_AL {
            get {
                return ResourceManager.GetString("UnidadeFederativa_AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazonas.
        /// </summary>
        internal static string UnidadeFederativa_AM {
            get {
                return ResourceManager.GetString("UnidadeFederativa_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amapá.
        /// </summary>
        internal static string UnidadeFederativa_AP {
            get {
                return ResourceManager.GetString("UnidadeFederativa_AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahia.
        /// </summary>
        internal static string UnidadeFederativa_BA {
            get {
                return ResourceManager.GetString("UnidadeFederativa_BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceará.
        /// </summary>
        internal static string UnidadeFederativa_CE {
            get {
                return ResourceManager.GetString("UnidadeFederativa_CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distrito Federal.
        /// </summary>
        internal static string UnidadeFederativa_DF {
            get {
                return ResourceManager.GetString("UnidadeFederativa_DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espírito Santo.
        /// </summary>
        internal static string UnidadeFederativa_ES {
            get {
                return ResourceManager.GetString("UnidadeFederativa_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goiás.
        /// </summary>
        internal static string UnidadeFederativa_GO {
            get {
                return ResourceManager.GetString("UnidadeFederativa_GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maranhão.
        /// </summary>
        internal static string UnidadeFederativa_MA {
            get {
                return ResourceManager.GetString("UnidadeFederativa_MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minas Gerais.
        /// </summary>
        internal static string UnidadeFederativa_MG {
            get {
                return ResourceManager.GetString("UnidadeFederativa_MG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mato Grosso do Sul.
        /// </summary>
        internal static string UnidadeFederativa_MS {
            get {
                return ResourceManager.GetString("UnidadeFederativa_MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mato Grosso.
        /// </summary>
        internal static string UnidadeFederativa_MT {
            get {
                return ResourceManager.GetString("UnidadeFederativa_MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacional.
        /// </summary>
        internal static string UnidadeFederativa_NA {
            get {
                return ResourceManager.GetString("UnidadeFederativa_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pará.
        /// </summary>
        internal static string UnidadeFederativa_PA {
            get {
                return ResourceManager.GetString("UnidadeFederativa_PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraíba.
        /// </summary>
        internal static string UnidadeFederativa_PB {
            get {
                return ResourceManager.GetString("UnidadeFederativa_PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pernambuco.
        /// </summary>
        internal static string UnidadeFederativa_PE {
            get {
                return ResourceManager.GetString("UnidadeFederativa_PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piauí.
        /// </summary>
        internal static string UnidadeFederativa_PI {
            get {
                return ResourceManager.GetString("UnidadeFederativa_PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraná.
        /// </summary>
        internal static string UnidadeFederativa_PR {
            get {
                return ResourceManager.GetString("UnidadeFederativa_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rio de Janeiro.
        /// </summary>
        internal static string UnidadeFederativa_RJ {
            get {
                return ResourceManager.GetString("UnidadeFederativa_RJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rio Grande do Norte.
        /// </summary>
        internal static string UnidadeFederativa_RN {
            get {
                return ResourceManager.GetString("UnidadeFederativa_RN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rondônia.
        /// </summary>
        internal static string UnidadeFederativa_RO {
            get {
                return ResourceManager.GetString("UnidadeFederativa_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roraima.
        /// </summary>
        internal static string UnidadeFederativa_RR {
            get {
                return ResourceManager.GetString("UnidadeFederativa_RR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rio Grande do Sul.
        /// </summary>
        internal static string UnidadeFederativa_RS {
            get {
                return ResourceManager.GetString("UnidadeFederativa_RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Santa Catarina.
        /// </summary>
        internal static string UnidadeFederativa_SC {
            get {
                return ResourceManager.GetString("UnidadeFederativa_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sergipe.
        /// </summary>
        internal static string UnidadeFederativa_SE {
            get {
                return ResourceManager.GetString("UnidadeFederativa_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to São Paulo.
        /// </summary>
        internal static string UnidadeFederativa_SP {
            get {
                return ResourceManager.GetString("UnidadeFederativa_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tocantins.
        /// </summary>
        internal static string UnidadeFederativa_TO {
            get {
                return ResourceManager.GetString("UnidadeFederativa_TO", resourceCulture);
            }
        }
    }
}
