<?xml version="1.0" encoding="utf-8"?><Database Name="LibraDB" Class="LibraDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DOSLIMAS\MESKLARSOLUTIONS;Initial Catalog=LibraDB;Persist Security Info=True;User ID=sa" SettingsObjectName="Libra.Entity.Properties.Settings" SettingsPropertyName="LibraDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRole">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="RoleId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserClaims" Member="AspNetUserClaims">
    <Type Name="AspNetUserClaim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserLogins" Member="AspNetUserLogins">
    <Type Name="AspNetUserLogin">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRole">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetRole" ThisKey="RoleId" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUserClaims" ThisKey="Id" OtherKey="UserId" Type="AspNetUserClaim" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUserLogins" ThisKey="Id" OtherKey="UserId" Type="AspNetUserLogin" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="UserId" Type="AspNetUserRole" />
      <Association Name="AspNetUser_USUARIO" Member="USUARIOs" ThisKey="Id" OtherKey="ASPNETUSERID" Type="USUARIO" />
    </Type>
  </Table>
  <Table Name="dbo.USUARIOS" Member="USUARIOs">
    <Type Name="USUARIO">
      <Column Name="USUARIOID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TELEFONE" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="SEXO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CPF" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="DATANASCIMENTO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DATACADASTRO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ASPNETUSERID" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="USUARIO_LOG" Member="LOGs" ThisKey="USUARIOID" OtherKey="IDUSUARIO" Type="LOG" />
      <Association Name="USUARIO_USUARIOPERFI" Member="USUARIOPERFIs" ThisKey="USUARIOID" OtherKey="USUARIOID" Type="USUARIOPERFI" />
      <Association Name="USUARIO_USUARIOUNIDADE" Member="USUARIOUNIDADEs" ThisKey="USUARIOID" OtherKey="USUARIOID" Type="USUARIOUNIDADE" />
      <Association Name="USUARIO_PRODUTO" Member="PRODUTOs" ThisKey="USUARIOID" OtherKey="CRIADOPOR" Type="PRODUTO" />
      <Association Name="AspNetUser_USUARIO" Member="AspNetUser" ThisKey="ASPNETUSERID" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOGS" Member="LOGs">
    <Type Name="LOG">
      <Column Name="IDLOG" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DATAALTERACAO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TABELA" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TIPO" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="QUERY" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CLAUSULAWHERE" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="IP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDUSUARIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="USUARIO_LOG" Member="USUARIO" ThisKey="IDUSUARIO" OtherKey="USUARIOID" Type="USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UNIDADES" Member="UNIDADEs">
    <Type Name="UNIDADE">
      <Column Name="UNIDADEID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="APELIDO" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UF" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="CIDADE" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="BAIRRO" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="LOGRADOURO" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="NUMERO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="COMPLEMENTO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CEP" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="TEL1" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="TEL2" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="FAX" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EMAIL1" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="EMAIL2" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="OBSERVACAO" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="ATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TIPOUNIDADE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="UNIDADE_USUARIOUNIDADE" Member="USUARIOUNIDADEs" ThisKey="UNIDADEID" OtherKey="UNIDADEID" Type="USUARIOUNIDADE" />
    </Type>
  </Table>
  <Table Name="dbo.USUARIOPERFIS" Member="USUARIOPERFIs">
    <Type Name="USUARIOPERFI">
      <Column Name="USUARIOPERFILID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USUARIOID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PERFILID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="USUARIO_USUARIOPERFI" Member="USUARIO" ThisKey="USUARIOID" OtherKey="USUARIOID" Type="USUARIO" IsForeignKey="true" />
      <Association Name="PERFI_USUARIOPERFI" Member="PERFI" ThisKey="PERFILID" OtherKey="PERFILID" Type="PERFI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.USUARIOUNIDADES" Member="USUARIOUNIDADEs">
    <Type Name="USUARIOUNIDADE">
      <Column Name="USUARIOUNIDADESID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USUARIOID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UNIDADEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UNIDADE_USUARIOUNIDADE" Member="UNIDADE" ThisKey="UNIDADEID" OtherKey="UNIDADEID" Type="UNIDADE" IsForeignKey="true" />
      <Association Name="USUARIO_USUARIOUNIDADE" Member="USUARIO" ThisKey="USUARIOID" OtherKey="USUARIOID" Type="USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PERFIS" Member="PERFIs">
    <Type Name="PERFI">
      <Column Name="PERFILID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DATACADASTRO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SOMENTELEITURA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PERFI_USUARIOPERFI" Member="USUARIOPERFIs" ThisKey="PERFILID" OtherKey="PERFILID" Type="USUARIOPERFI" />
      <Association Name="PERFI_FUNCIONALIDADEPERFI" Member="FUNCIONALIDADEPERFIs" ThisKey="PERFILID" OtherKey="PERFILID" Type="FUNCIONALIDADEPERFI" />
    </Type>
  </Table>
  <Table Name="dbo.FUNCIONALIDADES" Member="FUNCIONALIDADEs">
    <Type Name="FUNCIONALIDADE">
      <Column Name="FUNCIONALIDADEID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NOMEARQUIVO" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MENUPAIID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="FUNCIONALIDADE_FUNCIONALIDADEPERFI" Member="FUNCIONALIDADEPERFIs" ThisKey="FUNCIONALIDADEID" OtherKey="FUNCIONALIDADEID" Type="FUNCIONALIDADEPERFI" />
    </Type>
  </Table>
  <Table Name="dbo.FUNCIONALIDADEPERFIS" Member="FUNCIONALIDADEPERFIs">
    <Type Name="FUNCIONALIDADEPERFI">
      <Column Name="FUNCIONALIDADEPERFILID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FUNCIONALIDADEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PERFILID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FUNCIONALIDADE_FUNCIONALIDADEPERFI" Member="FUNCIONALIDADE" ThisKey="FUNCIONALIDADEID" OtherKey="FUNCIONALIDADEID" Type="FUNCIONALIDADE" IsForeignKey="true" />
      <Association Name="PERFI_FUNCIONALIDADEPERFI" Member="PERFI" ThisKey="PERFILID" OtherKey="PERFILID" Type="PERFI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CARACTERISTICASDIVERSASPRODUTOS" Member="CARACTERISTICASDIVERSASPRODUTOs">
    <Type Name="CARACTERISTICASDIVERSASPRODUTO">
      <Column Name="CARACTERISTICASDIVERSASPRODUTOID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CARACTERISTICASDIVERSASPRODUTO_PRODUTOCARACTERISTICADIVERSA" Member="PRODUTOCARACTERISTICADIVERSAs" ThisKey="CARACTERISTICASDIVERSASPRODUTOID" OtherKey="CARACTERISTICASDIVERSASPRODUTOID" Type="PRODUTOCARACTERISTICADIVERSA" />
    </Type>
  </Table>
  <Table Name="dbo.CORPRODUTOS" Member="CORPRODUTOs">
    <Type Name="CORPRODUTO">
      <Column Name="CORPRODUTOID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CORPRODUTO_PRODUTO" Member="PRODUTOs" ThisKey="CORPRODUTOID" OtherKey="CORID" Type="PRODUTO" />
    </Type>
  </Table>
  <Table Name="dbo.DIMENSOESPRODUTOS" Member="DIMENSOESPRODUTOs">
    <Type Name="DIMENSOESPRODUTO">
      <Column Name="DIMENSOESPRODUTOID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LARGURA" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="COMPRIMENTO" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="ALTURA" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRICAO" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DIMENSOESPRODUTO_PRODUTO" Member="PRODUTOs" ThisKey="DIMENSOESPRODUTOID" OtherKey="DIMENSOESID" Type="PRODUTO" />
    </Type>
  </Table>
  <Table Name="dbo.FABRICANTEPRODUTOS" Member="FABRICANTEPRODUTOs">
    <Type Name="FABRICANTEPRODUTO">
      <Column Name="FABRICANTEPRODUTOID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="FABRICANTEPRODUTO_PRODUTO" Member="PRODUTOs" ThisKey="FABRICANTEPRODUTOID" OtherKey="FABRICANTEID" Type="PRODUTO" />
    </Type>
  </Table>
  <Table Name="dbo.MARCAPRODUTOS" Member="MARCAPRODUTOs">
    <Type Name="MARCAPRODUTO">
      <Column Name="MARCAPRODUTOID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MARCAPRODUTO_PRODUTO" Member="PRODUTOs" ThisKey="MARCAPRODUTOID" OtherKey="MARCAID" Type="PRODUTO" />
    </Type>
  </Table>
  <Table Name="dbo.MODELOPRODUTOS" Member="MODELOPRODUTOs">
    <Type Name="MODELOPRODUTO">
      <Column Name="MODELOPRODUTOID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MODELOPRODUTO_PRODUTO" Member="PRODUTOs" ThisKey="MODELOPRODUTOID" OtherKey="MODELOID" Type="PRODUTO" />
    </Type>
  </Table>
  <Table Name="dbo.TIPOPRODUTOS" Member="TIPOPRODUTOs">
    <Type Name="TIPOPRODUTO">
      <Column Name="TIPOPRODUTOID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ATIVO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TIPOPRODUTO_PRODUTO" Member="PRODUTOs" ThisKey="TIPOPRODUTOID" OtherKey="TIPOPRODUTOID" Type="PRODUTO" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUTOS" Member="PRODUTOs">
    <Type Name="PRODUTO">
      <Column Name="PRODUTOID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TIPOPRODUTOID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FABRICANTEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MARCAID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MODELOID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIMENSOESID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CORID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DESCRICAO" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PESO" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="DISPONIVELCOMERCIO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DATACRIACAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CRIADOPOR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PRODUTO_PRODUTOCARACTERISTICADIVERSA" Member="PRODUTOCARACTERISTICADIVERSAs" ThisKey="PRODUTOID" OtherKey="PRODUTOID" Type="PRODUTOCARACTERISTICADIVERSA" />
      <Association Name="CORPRODUTO_PRODUTO" Member="CORPRODUTO" ThisKey="CORID" OtherKey="CORPRODUTOID" Type="CORPRODUTO" IsForeignKey="true" />
      <Association Name="USUARIO_PRODUTO" Member="USUARIO" ThisKey="CRIADOPOR" OtherKey="USUARIOID" Type="USUARIO" IsForeignKey="true" />
      <Association Name="DIMENSOESPRODUTO_PRODUTO" Member="DIMENSOESPRODUTO" ThisKey="DIMENSOESID" OtherKey="DIMENSOESPRODUTOID" Type="DIMENSOESPRODUTO" IsForeignKey="true" />
      <Association Name="FABRICANTEPRODUTO_PRODUTO" Member="FABRICANTEPRODUTO" ThisKey="FABRICANTEID" OtherKey="FABRICANTEPRODUTOID" Type="FABRICANTEPRODUTO" IsForeignKey="true" />
      <Association Name="MARCAPRODUTO_PRODUTO" Member="MARCAPRODUTO" ThisKey="MARCAID" OtherKey="MARCAPRODUTOID" Type="MARCAPRODUTO" IsForeignKey="true" />
      <Association Name="MODELOPRODUTO_PRODUTO" Member="MODELOPRODUTO" ThisKey="MODELOID" OtherKey="MODELOPRODUTOID" Type="MODELOPRODUTO" IsForeignKey="true" />
      <Association Name="TIPOPRODUTO_PRODUTO" Member="TIPOPRODUTO" ThisKey="TIPOPRODUTOID" OtherKey="TIPOPRODUTOID" Type="TIPOPRODUTO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUTOCARACTERISTICADIVERSAS" Member="PRODUTOCARACTERISTICADIVERSAs">
    <Type Name="PRODUTOCARACTERISTICADIVERSA">
      <Column Name="PRODUTOCARACTERISTICADIVERSAID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PRODUTOID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARACTERISTICASDIVERSASPRODUTOID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CARACTERISTICASDIVERSASPRODUTO_PRODUTOCARACTERISTICADIVERSA" Member="CARACTERISTICASDIVERSASPRODUTO" ThisKey="CARACTERISTICASDIVERSASPRODUTOID" OtherKey="CARACTERISTICASDIVERSASPRODUTOID" Type="CARACTERISTICASDIVERSASPRODUTO" IsForeignKey="true" />
      <Association Name="PRODUTO_PRODUTOCARACTERISTICADIVERSA" Member="PRODUTO" ThisKey="PRODUTOID" OtherKey="PRODUTOID" Type="PRODUTO" IsForeignKey="true" />
    </Type>
  </Table>
</Database>